/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintbasico2d;

import sm.ftm.iu.Lienzo2D;
import sm.ftm.graficos.Formas;

/**
 *
 * @author thejoker
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInterna
     */
    
    private VentanaPrincipal parent = null;
  
    public VentanaInterna(VentanaPrincipal parent) {
        initComponents();
        this.parent = parent;
        
        this.setTitle("Lienzo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo2D = new sm.ftm.iu.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo2D, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public Lienzo2D getLienzo2D(){
        return lienzo2D;
    }
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
        if(this.lienzo2D.getForma() == Formas.Punto)
            this.parent.ToggleButtonPuntos.setSelected(true);
       
        if(this.lienzo2D.getForma() == Formas.Linea)
            this.parent.ToggleButtonLinea.setSelected(true);
        
        if(this.lienzo2D.getForma() == Formas.Rectangulo)
            this.parent.ToggleButtonRect.setSelected(true);
        
        if(this.lienzo2D.getForma() == Formas.Ovalo)
            this.parent.ToggleButtonElip.setSelected(true);
        
        this.parent.CheckBoxRelleno.setSelected(this.lienzo2D.isRelleno());
        this.parent.CheckBoxTrans.setSelected(this.lienzo2D.isTransparencia());
        this.parent.CheckBoxAlisar.setSelected(this.lienzo2D.isAlisar());
        this.parent.CheckBoxEditar.setSelected(this.lienzo2D.isEditar());
         
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.ftm.iu.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
