/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintbasico2d;

import java.awt.BasicStroke;
import java.awt.Color;
import javax.swing.JSpinner;
import sm.ftm.iu.Lienzo2D;
import sm.ftm.iu.Formas;
import sm.ftm.iu.Lienzo2DImagen;

/**
 *
 * @author thejoker
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInterna
     */
    
    private VentanaPrincipal parent = null;
  
    public VentanaInterna(VentanaPrincipal parent) {
        initComponents();
        this.parent = parent;
        
        this.setTitle("Lienzo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2DImagen = new sm.ftm.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout lienzo2DImagenLayout = new javax.swing.GroupLayout(lienzo2DImagen);
        lienzo2DImagen.setLayout(lienzo2DImagenLayout);
        lienzo2DImagenLayout.setHorizontalGroup(
            lienzo2DImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        lienzo2DImagenLayout.setVerticalGroup(
            lienzo2DImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2DImagen);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public Lienzo2DImagen getLienzo2DImagen(){
        return lienzo2DImagen;
    }
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
        if(this.lienzo2DImagen.getForma() == Formas.Punto)
            this.parent.ToggleButtonPuntos.setSelected(true);
       
        if(this.lienzo2DImagen.getForma() == Formas.Linea)
            this.parent.ToggleButtonLinea.setSelected(true);
        
        if(this.lienzo2DImagen.getForma() == Formas.Rectangulo)
            this.parent.ToggleButtonRect.setSelected(true);
        
        if(this.lienzo2DImagen.getForma() == Formas.Elipse)
            this.parent.ToggleButtonElip.setSelected(true);
        
        if(this.lienzo2DImagen.getColor() == Color.BLACK)
            this.parent.ToggleButtonNegro.setSelected(true);
        
        if(this.lienzo2DImagen.getColor() == Color.RED)
            this.parent.ToggleButtonRojo.setSelected(true);
        
        if(this.lienzo2DImagen.getColor() == Color.BLUE)
            this.parent.ToggleButtonAzul.setSelected(true);
        
        if(this.lienzo2DImagen.getColor() == Color.WHITE)
            this.parent.ToggleButtonBlanco.setSelected(true);
        
        if(this.lienzo2DImagen.getColor() == Color.YELLOW)
            this.parent.ToggleButtonAmarillo.setSelected(true);
        
        if(this.lienzo2DImagen.getColor() == Color.GREEN)
            this.parent.ToggleButtonVerde.setSelected(true);
        
        BasicStroke s = (BasicStroke) this.lienzo2DImagen.getStroke();
        this.parent.SpinnerGrosor.setValue(this.lienzo2DImagen.getStrokeWidth().intValue());
        
        this.parent.CheckBoxRelleno.setSelected(this.lienzo2DImagen.isRelleno());
        this.parent.CheckBoxTrans.setSelected(this.lienzo2DImagen.isTransparencia());
        this.parent.CheckBoxAlisar.setSelected(this.lienzo2DImagen.isAlisar());
        this.parent.CheckBoxEditar.setSelected(this.lienzo2DImagen.isEditar()); 
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.ftm.iu.Lienzo2DImagen lienzo2DImagen;
    // End of variables declaration//GEN-END:variables
}
