/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paintbasico2d;

import java.awt.image.BufferedImage;

/**
 *
 * @author thejoker
 */
public class VentanaInternaSM extends javax.swing.JInternalFrame {

    /**
     * Creates new form VENTANAINTERNAsm
     */
    public VentanaInternaSM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // getImage shot camara
   
    public BufferedImage getImage(){
        return null;
    }
    
    public BufferedImage getShot(){
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
