/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import java.awt.GraphicsEnvironment;

/**
 *
 * @author thejoker
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        this.setSize(700, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo = new aplicacion.Lienzo();
        jPanel1 = new javax.swing.JPanel();
        CheckBoxEdicion = new javax.swing.JCheckBox();
        jCheckBoxRelleno = new javax.swing.JCheckBox();
        GraphicsEnvironment ge;
        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String []fuentesSistema = ge.getAvailableFontFamilyNames();
        jComboBoxFuentes = new javax.swing.JComboBox<>(fuentesSistema);
        jCheckBoxVentana = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CheckBoxEdicion.setText("Edición");
        CheckBoxEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxEdicionActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBoxEdicion);

        jCheckBoxRelleno.setText("Relleno");
        jPanel1.add(jCheckBoxRelleno);

        jPanel1.add(jComboBoxFuentes);

        jCheckBoxVentana.setText("Efecto ventana");
        jPanel1.add(jCheckBoxVentana);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxEdicionActionPerformed
        lienzo.editar = !lienzo.editar; 
    }//GEN-LAST:event_CheckBoxEdicionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxEdicion;
    private javax.swing.JCheckBox jCheckBoxRelleno;
    private javax.swing.JCheckBox jCheckBoxVentana;
    private javax.swing.JComboBox<String> jComboBoxFuentes;
    private javax.swing.JPanel jPanel1;
    private aplicacion.Lienzo lienzo;
    // End of variables declaration//GEN-END:variables
}
