/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sm.ftm.ui;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 * Clase que hereda de Lienzo2D y agrega las funciones necesarias 
 * para asignar una imagen al lienzo y poder pintar en ella.
 * 
 * @author thejoker
 */
public class Lienzo2DImagen extends Lienzo2D {

    /**
     * Creates new form Lienzo2DImagen
     */
    public Lienzo2DImagen() {
        initComponents();
        img = null;
        drawVector = false;
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(img!=null) g.drawImage(img,0,0,this);
    }
    
    /**
     * Función que devuele la imagen
     * @return the Img
     */
    public BufferedImage getImg(){
        return img;
    }
    
    /**
     * Función que devuelve la imagen con las figuras
     * @param drawVector
     * @return the Img
     */
    public BufferedImage getImg(boolean drawVector) {
        if (drawVector) {
            BufferedImage imgOut =  new BufferedImage(img.getWidth(), img.getHeight(), img.getType());
            //Transparencia
            this.paint(imgOut.createGraphics());
            return imgOut;
        }
        else
            return img;
    }

    /**
     * Función que establece la imagen en el lienzo
     * @param img
     */
    public void setImg(BufferedImage img) {
        this.img = img;
        if(img!=null) {
            setPreferredSize(new Dimension(img.getWidth(),img.getHeight()));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    /**
     *  Imagen cargada
     */
    private BufferedImage img;
    
    /**
     * booleano asociado a la hora de dibujar las figuras
     */
    private boolean drawVector;
}
