/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.paint;

import java.awt.AWTException;
import java.awt.AlphaComposite;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Composite;
import java.awt.Robot;
import java.util.logging.Level;
import java.util.logging.Logger;
import proyecto.paint.VentanaPrincipal;
import sm.ftm.ui.Lienzo2DImagen;
import sm.ftm.graficos.Forma;

/**
 *
 * @author thejoker
 */
public class VentanaInternaImagen extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInternaImagen
     */
    public VentanaInternaImagen (VentanaPrincipal parent){
        initComponents();
        
        this.setTitle("Lienzo");
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        lienzo2DImagen = new sm.ftm.ui.Lienzo2DImagen();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane.setBackground(new java.awt.Color(204, 204, 204));

        lienzo2DImagen.setBackground(new java.awt.Color(204, 204, 204));
        lienzo2DImagen.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DImagenMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DImagenLayout = new javax.swing.GroupLayout(lienzo2DImagen);
        lienzo2DImagen.setLayout(lienzo2DImagenLayout);
        lienzo2DImagenLayout.setHorizontalGroup(
            lienzo2DImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );
        lienzo2DImagenLayout.setVerticalGroup(
            lienzo2DImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jScrollPane.setViewportView(lienzo2DImagen);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzo2DImagenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DImagenMouseMoved
        try {
            Robot robot = new Robot();
            if( 0 <= evt.getX() && evt.getX() <= this.getLienzo2DImagen().getWidth() && 0 <= evt.getY() && evt.getY() <= this.getLienzo2DImagen().getHeight()){
                Color pixel = robot.getPixelColor(evt.getX(), evt.getY());
                this.parent.LabelColor.setText("R: "+ pixel.getRed() +" G: "+ pixel.getGreen() +" B: "+ pixel.getBlue());
            }else
                this.parent.LabelColor.setText("R:  G:  B: ");
        } catch (AWTException ex) {
            Logger.getLogger(VentanaInternaImagen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if( 0 <= evt.getX() && evt.getX() <= this.getLienzo2DImagen().getWidth() && 0 <= evt.getY() && evt.getY() <= this.getLienzo2DImagen().getHeight())
            this.parent.LabelCoordenadas.setText("Coordenadas: ("+ evt.getX() + "," + evt.getY() + ")");
        else
            this.parent.LabelCoordenadas.setText("Coordenadas: (x , y)");
    }//GEN-LAST:event_lienzo2DImagenMouseMoved

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        if(this.lienzo2DImagen.getShape().getForma() == Forma.POINT)
            this.parent.ToggleButtonPuntos.setSelected(true);
       
        if(this.lienzo2DImagen.getShape().getForma() == Forma.LINE)
            this.parent.ToggleButtonLinea.setSelected(true);
        
        if(this.lienzo2DImagen.getShape().getForma() == Forma.RECTANGLE)
            this.parent.ToggleButtonRectangulo.setSelected(true);
        
        if(this.lienzo2DImagen.getShape().getForma() == Forma.ELLIPSE)
            this.parent.ToggleButtonElipse.setSelected(true);
        
        if(this.lienzo2DImagen.getShape().getForma() == Forma.CURVE)
            this.parent.ToggleButtonCurva.setSelected(true);
        
        if(this.lienzo2DImagen.getShape().getForma() == Forma.AREA)
            this.parent.ToggleButtonArea.setSelected(true);
        
        if(this.lienzo2DImagen.getShape().getForma() == Forma.FREE)
            this.parent.ToggleButtonTrazoLibre.setSelected(true);
        
        this.parent.ToggleButtonMover.setSelected(this.lienzo2DImagen.isMover());
        
        this.parent.ButtonColorTrazo.setBackground(this.lienzo2DImagen.getShape().getColorTrazo());
        this.parent.ButtonColorRelleno.setBackground(this.lienzo2DImagen.getShape().getColorerellenoSimple());
        
        if(this.lienzo2DImagen.getShape().getTipotrazo() == "Continua")
            this.parent.ComboBoxTrazo.setSelectedItem("Continua");
        else
            this.parent.ComboBoxTrazo.setSelectedItem("Punteada");
        
        this.parent.SpinnerGrosor.setValue(this.lienzo2DImagen.getShape().getStrokeWidth().intValue());
        
        if(!this.lienzo2DImagen.getShape().isRellenoSimple() && !this.lienzo2DImagen.getShape().isRellenoGradienteH() && !this.lienzo2DImagen.getShape().isRellenoGradienteV())
            this.parent.ToggleButtonSinRelleno.setSelected(true);
        
        this.parent.ToggleButtonRellenoSimple.setSelected(this.lienzo2DImagen.getShape().isRellenoSimple());
        this.parent.ToggleButtonRellenoGradienteH.setSelected(this.lienzo2DImagen.getShape().isRellenoGradienteH());
        this.parent.ToggleButtonRellenoGradienteV.setSelected(this.lienzo2DImagen.getShape().isRellenoGradienteV());
        
        this.parent.ToggleButtonAlisar.setSelected(this.lienzo2DImagen.getShape().isAlisado());
        this.parent.SliderTransparencia.setValue((int) (this.lienzo2DImagen.getShape().getCompvalue()*100));
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        parent.setAlto(0);
        parent.setAncho(0);
    }//GEN-LAST:event_formInternalFrameClosed

    /**
     * @return the lienzo2DImagen
     */
    public Lienzo2DImagen getLienzo2DImagen() {
        return lienzo2DImagen;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private sm.ftm.ui.Lienzo2DImagen lienzo2DImagen;
    // End of variables declaration//GEN-END:variables
    private VentanaPrincipal parent;
}
